spring:
  debug: true
  jpa:
    database: hsql
    database-platform: org.hibernate.dialect.HSQLDialect
    orm: META-INF/orm.xml
    open-in-view: false
  datasource:
    url: jdbc:hsqldb:mem:dataSource
    username: sa
    password: 
    driver-class-name: org.hsqldb.jdbcDriver
# Logging Configurations
logging:
  level:
    root: info
    org.hibernate: warn
    fr.training.spring.shop: debug
    org.springframework.batch: trace
    file: myfile.log
    path: logs
    pattern:
        console: "%date{yyyy-MM-dd HH:mm:ss.SSSXXX} | %-5level | %X{IP} | %X{HostName} | %X{AppName} | %X{X-B3-TraceId:-} | %X{X-B3-SpanId:-} | %X{X-Span-Export:-} | %X{UserID} | %X{Marker} | %logger{36} - %msg%n"                
    